#!/bin/sh

APPID=org.webosinternals.tailor
NSRVID=org.webosinternals.tailor.node
CSRVID=org.webosinternals.tailor

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the node service executable
rm -f /var/usr/sbin/${NSRVID}

# Stop the node service if running
/usr/bin/luna-send -n 1 palm://${NSRVID}/__quit '{}'

# Remove the C service executable
rm -f /var/usr/sbin/${CSRVID}

# Remove the dbus service
rm -f /var/palm/ls2/services/prv/${CSRVID}.service
rm -f /var/palm/ls2/services/pub/${CSRVID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${CSRVID}.json /var/palm/ls2/roles/pub/${CSRVID}.json

# Stop the C service if running
/sbin/stop ${CSRVID} || true
/usr/bin/killall -9 ${CSRVID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${CSRVID}

exit 0
